apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-mini-basket

spec:
  replicas: 1

  template:
    spec:
      containers:
        - name: apps-mini-basket
          image: apetitoebusinesssolutions.azurecr.io/meinapetito-apps-mini-basket:latest
          env:
            - name: VUE_APP_BASKET_BASE_URL
              value: https://shared-partnerportalbasket.stage.apebs.de/basket
            - name: VUE_APP_BASKET_INITIALIZATION_URL
              value: https://shared-partnerportalbasket.stage.apebs.de/shoppingsession