apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-application-guard

spec:
  replicas: 1

  template:
    spec:
      containers:
        - name: apps-application-guard
          image: apetitoebusinesssolutions.azurecr.io/meinapetito-apps-application-guard:latest
          env:
            - name: VUE_APP_ENVIRONMENT
              value: Staging
