apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-faq

spec:
  selector:
    matchLabels:
      app: apps-faq

  replicas: 3

  template:
    metadata:
      labels:
        app: apps-faq

    spec:
      containers:
        - name: apps-faq
          image: apetitoebusinesssolutions.azurecr.io/meinapetito-apps-faq:latest
          imagePullPolicy: Always
          
          env:
            - name: VUE_APP_MEINAPETITO_PORTAL_BASE_URL
              value: https://mein.apetito.de/api
            - name: VUE_APP_MEINAPETITO_GRAPHQL_URL
              value: https://mein.apetito.de/api/graphql
         
