apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-faq

spec:
  replicas: 1

  template:
    spec:
      containers:
        - name: apps-faq
          image: apetitoebusinesssolutions.azurecr.io/meinapetito-apps-faq:latest
          env:
            - name: VUE_APP_ENVIRONMENT
              value: Staging
            - name: VUE_APP_MEINAPETITO_GRAPHQL_URL
              value: https://stage-meinapetito.apebs.de/api/graphql
            - name: VUE_APP_PRISMIC_REPOSITORY
              value: meinapetito
            - name: VUE_APP_MEINAPETITO_PORTAL_BASE_URL
              value: https://stage-meinapetito.apebs.de/api
            - name: VUE_APP_IPRODA_API_BASE_URL
              value: https://api.apetito.de/article/iproda
